// notion.ts
import { Client } from '@notionhq/client';
import type { BobAnalysisResult, ChangelogAudiences, NotionPublishResult } from './types.js';
import type { Config } from './cli/config';

// --- block builders ---

function divider() {
    return { object: 'block' as const, type: 'divider' as const, divider: {} };
}

function heading2(text: string) {
    return {
        object: 'block' as const,
        type: 'heading_2' as const,
        heading_2: {
            rich_text: [{ type: 'text' as const, text: { content: text } }],
        },
    };
}

function paragraph(text: string) {
    return {
        object: 'block' as const,
        type: 'paragraph' as const,
        paragraph: {
            rich_text: [{ type: 'text' as const, text: { content: text } }],
        },
    };
}

function callout(text: string, emoji: string) {
    return {
        object: 'block' as const,
        type: 'callout' as const,
        callout: {
            rich_text: [{ type: 'text' as const, text: { content: text } }],
            icon: { type: 'emoji' as const, emoji },
        },
    };
}

function toggle(title: string, children: any[]) {
    return {
        object: 'block' as const,
        type: 'toggle' as const,
        toggle: {
            rich_text: [{ type: 'text' as const, text: { content: title } }],
            children,
        },
    };
}

function bulletItem(text: string) {
    return {
        object: 'block' as const,
        type: 'bulleted_list_item' as const,
        bulleted_list_item: {
            rich_text: [{ type: 'text' as const, text: { content: text } }],
        },
    };
}

// --- chunk utility (100 block API limit) ---
async function appendChunked(notion: Client, pageId: string, blocks: any[]) {
    const chunkSize = 100;
    for (let i = 0; i < blocks.length; i += chunkSize) {
        await notion.blocks.children.append({
            block_id: pageId,
            children: blocks.slice(i, i + chunkSize),
        });
    }
}

// --- idempotency check ---
export async function findExistingPage(
    notion: Client,
    prNumber: number,
    repo: string,
    parentPageId: string
): Promise<string | null> {
    const res = await notion.search({
        query: `[${repo}] PR #${prNumber}`,
        filter: { property: 'object', value: 'page' },
    });

    const match = res.results.find(
        (r: any) => r.object === 'page' && r.parent?.page_id === parentPageId
    );

    return match ? match.id : null;
}

// --- main publish function ---
export async function publishToNotion(
    analysis: BobAnalysisResult,
    audiences: ChangelogAudiences,
    config: Config
): Promise<string> {
    // Initialize Notion client with config
    const notion = new Client({
        auth: config.notion.token,
        notionVersion: '2026-03-11',
    });
    const title = `[${analysis.repo}] PR #${analysis.pr_number} — ${analysis.pr_title}`;
    const date = new Date().toISOString().split('T')[0];
    const changeTypeLabel = analysis.change_types.map(t => t.toUpperCase()).join(' · ');

    // check for existing page first
    const existingId = await findExistingPage(notion, analysis.pr_number, analysis.repo, config.notion.parentPageId);
    if (existingId) {
        console.log(`Page already exists for PR #${analysis.pr_number}, skipping.`);
        return existingId;
    }

    // create the page
    const page = await notion.pages.create({
        parent: { page_id: config.notion.parentPageId },
        icon: { type: 'emoji', emoji: '📋' },
        properties: {
            title: {
                title: [{ type: 'text', text: { content: title } }],
            },
        },
    });

    const pageId = page.id;

    // build the full block structure
    const blocks = [

        // --- cover info callout ---
        callout(
            `${changeTypeLabel} · ${date} · ${analysis.repo} · PR #${analysis.pr_number} · Generated by ChangeNarrator`,
            '🤖'
        ),

        // --- stats row ---
        callout(
            `Files changed: ${analysis.files_skipped.length > 0 ? `some patches unavailable (${analysis.files_skipped.length} files skipped)` : 'all files analyzed'}   ·   Modules affected: ${analysis.affected_modules.length}   ·   Breaking changes: ${analysis.breaking_changes ? '⚠️ Yes' : '✅ None'}`,
            '📊'
        ),

        divider(),

        // --- breaking change warning (conditional) ---
        ...(analysis.breaking_changes
            ? [callout(`⚠️ Breaking change: ${analysis.breaking_change_details}`, '⚠️'), divider()]
            : []
        ),

        // --- affected modules ---
        heading2('Affected Modules'),
        ...analysis.affected_modules.map(m => bulletItem(m)),

        divider(),

        // --- for devs toggle ---
        toggle('🛠️ For Developers', [
            paragraph(audiences.devs),
        ]),

        // --- for pms toggle ---
        toggle('📈 For Product & Stakeholders', [
            paragraph(audiences.pms),
        ]),

        // --- for users toggle ---
        toggle('👤 For Users', [
            paragraph(audiences.users),
        ]),

        divider(),

        // --- technical summary ---
        heading2('Technical Summary'),
        paragraph(analysis.technical_summary),
    ];

    // append all blocks in chunks of 100
    await appendChunked(notion, pageId, blocks);

    console.log(`✅ Notion page created: https://notion.so/${pageId.replace(/-/g, '')}`);
    return pageId;
}